"""
projected_view.py

Represents a single 2D engineering drawing view generated from a
3D CAD model.

Examples:
- Front View
- Top View
- Right View
- Isometric View

Each view contains visible and hidden geometry that later modules
(DXF export, dimensions, drawing sheet) will use.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from app.projection.geometry2d import Geometry2D, BoundingBox2D


class ViewType(Enum):
    """Supported orthographic/isometric view directions."""

    FRONT = "Front"
    TOP = "Top"
    RIGHT = "Right"
    ISOMETRIC = "Isometric"


@dataclass(slots=True)
class ProjectedView:
    """
    Represents a single projected engineering drawing view.
    """

    view_type: ViewType

    # Geometry generated by the projection engine
    visible_geometry: list[Geometry2D] = field(default_factory=list)
    hidden_geometry: list[Geometry2D] = field(default_factory=list)

    # View properties
    bounding_box: BoundingBox2D | None = None
    scale: float = 1.0
    origin_x: float = 0.0
    origin_y: float = 0.0

    @property
    def total_entities(self) -> int:
        """Return the total number of projected entities."""
        return len(self.visible_geometry) + len(self.hidden_geometry)

    def clear(self) -> None:
        """Remove all projected geometry."""
        self.visible_geometry.clear()
        self.hidden_geometry.clear()